name: Deploy React to GitHub Pages

on:
  push:
    branches:
      - main  # Change this if your default branch is different

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: npm run build

      - name: Verify Build Directory
        run: ls -al build  # This will list the contents of the build folder to verify it exists

      - name: Deploy to GitHub Pages
        if: success()
        env:
          ALL_ACCESS_TOKEN_GIT: ${{ secrets.ALL_ACCESS_TOKEN_GIT }}
        run: |
          git config --global user.email "avish.kaushik20@gmail.com"
          git config --global user.name "AvishKaushik"
          npx gh-pages -d build -r "https://$ALL_ACCESS_TOKEN_GIT@github.com/AvishKaushik/sdg3-classifier.git"
